from typing import Any

# select * from X
def query1(data: list[dict[str, Any]]) -> list[dict[str, Any]]: ...

# select a, b from X
def query2(data: list[dict[str, Any]]) -> list[dict[str, Any]]: ...

# select a, b from X where y > 0
def query3(data: list[dict[str, Any]]) -> list[dict[str, Any]]: ...

# select sum(a) from X
def query4(data: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
